### ISSUE TITLE
Failled to start poxa with Erlang 20

### ISSUE THREAD

**Issue by balugege** [edgurgel/poxa#101]
When running ```ruby@dispatch1:~/poxa$` ./rel/poxa/bin/poxa start``` with those Versions:

```
Erlang/OTP 20 [RELEASE CANDIDATE 2] [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]    

Elixir 1.4.4
```

i get:     

```
copying /home/ruby/poxa/rel/poxa/releases/0.6.0/poxa.conf to /home/ruby/poxa/rel/poxa/running-config/poxa.conf ...
using /home/ruby/poxa/rel/poxa/running-config/poxa.conf to populate "/home/ruby/poxa/rel/poxa/running-config".
** (FunctionClauseError) no function clause matching in Conform.Translate.to_config/3
    (conform) lib/conform/translate.ex:64: Conform.Translate.to_config(%Conform.Schema{extends: [], import: [], mappings: [%Conform.Schema.Mapping{commented: false, datatype
: :integer, default: 8080, doc: "HTTP port", hidden: false, include_default: nil, name: "poxa.port", persist: true, see: "", to: "poxa.port", validators: []}, %Conform.Schem
a.Mapping{commented: false, datatype: :binary, default: "app_key", doc: "Pusher app key", hidden: false, include_default: nil, name: "poxa.app_key", persist: true, see: "",
to: "poxa.app_key", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :binary, default: "secret", doc: "Pusher secret", hidden: false, include_default: ni
l, name: "poxa.app_secret", persist: true, see: "", to: "poxa.app_secret", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :binary, default: "app_id", d
oc: "Pusher app id", hidden: false, include_default: nil, name: "poxa.app_id", persist: true, see: "", to: "poxa.app_id", validators: []}, %Conform.Schema.Mapping{commented:
 false, datatype: :binary, default: "gproc", doc: "Registry adapter", hidden: false, include_default: nil, name: "poxa.registry_adapter", persist: true, see: "", to: "poxa.r
egistry_adapter", validators: []}, %Conform.Schema.Mapping{commented: true, datatype: :atom, default: nil, doc: "Web hook endpoint", hidden: false, include_default: nil, nam
e: "poxa.web_hook", persist: true, see: "", to: "poxa.web_hook", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :boolean, default: false, doc: "HTTPS s
witch", hidden: false, include_default: nil, name: "poxa.ssl.enabled", persist: true, see: "", to: "poxa.ssl.enabled", validators: []}, %Conform.Schema.Mapping{commented: fa
lse, datatype: :integer, default: nil, doc: "HTTPS port", hidden: false, include_default: nil, name: "poxa.ssl.port", persist: true, see: "", to: "poxa.ssl.port", validators
: []}, %Conform.Schema.Mapping{commented: false, datatype: :binary, default: nil, doc: "PEM-encoded CA certificate path", hidden: false, include_default: nil, name: "poxa.ss
l.cacertfile", persist: true, see: "", to: "poxa.ssl.cacertfile", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :binary, default: nil, doc: "Path to u
ser certificate", hidden: false, include_default: nil, name: "poxa.ssl.certfile", persist: true, see: "", to: "poxa.ssl.certfile", validators: []}, %Conform.Schema.Mapping{c
ommented: false, datatype: :binary, default: nil, doc: "Path to the file containing the user's private PEM-encoded key", hidden: false, include_default: nil, name: "poxa.ssl
.keyfile", persist: true, see: "", to: "poxa.ssl.keyfile", validators: []}], transforms: [], validators: []}, [sasl: [errlog_type: :error], poxa: [port: 8080, app_key: "app_
key", app_secret: "secret", app_id: "app_id", registry_adapter: "gproc", web_hook: nil, ssl: [enabled: true, port: 8443, cacertfile: "/etc/nginx/ssl/root.crt", certfile: "/e
tc/nginx/ssl/ccl.crt", keyfile: "/etc/nginx/ssl/ccl.key"]]], #Reference<0.1910853577.3943563265.84090>)
    (conform) lib/conform.ex:92: Conform.process/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2
```
After downgrading erlang to Version 19 it works again as expected
```
Erlang/OTP 19 [erts-8.0] [source-6dc93c1] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.4
```

**Comment by edgurgel** [comment]
🤔 We may need to update conform. I know we are using an old version. I will have a look next weekend.

**Comment by edgurgel** [comment]
Master has a working version with Elixir 1.5 & Erlang 20. Soon a new release 🎉
