### ISSUE TITLE
Deploying to Heroku issue

### ISSUE THREAD

**Issue by 7osCraft** [edgurgel/poxa#113]
Hello,
When I try to deploy this project to heroku using the provided button it gives me an error.
Here's the log:
```
-----> Elixir app detected
-----> Checking Erlang and Elixir versions
       Will use the following versions:
       * Stack heroku-16
       * Erlang 17.0
       * Elixir 1.0.0 
-----> Will export the following config vars:
BUILDPACK_URL
       * MIX_ENV=prod
-----> Stack changed, will rebuild
-----> Fetching Erlang 17.0
-----> Installing Erlang 17.0 (changed)
-----> Fetching Elixir v1.0.0 for OTP 17
-----> Installing Elixir v1.0.0 (changed)
-----> Installing Hex
2018-01-30 13:31:40 URL:https://repo.hex.pm/installs/1.0.0/hex.ez [622262/622262] -> "/tmp/hex.ez" [1]
* creating /app/.mix/archives/hex.ez
-----> Installing rebar
* creating /app/.mix/rebar
-----> Fetching app dependencies with mix
13:31:44.528 [error] Task #PID<0.94.0> started from Hex.UpdateChecker terminating
Function: #Function<0.93999895/0 in Hex.UpdateChecker.handle_cast/2>
    Args: []
** (exit) an exception was raised:
    ** (Mix.Error) Insecure HTTPS request (peer verification disabled), please update to OTP 17.4 or later, or disable by setting the environment variable HEX_UNSAFE_HTTPS=1
        (mix) lib/mix.ex:235: Mix.raise/1
        (hex) lib/hex/http/ssl.ex:38: Hex.HTTP.SSL.secure_ssl?/0
        (hex) lib/hex/http/ssl.ex:49: Hex.HTTP.SSL.ssl_opts/1
        (hex) lib/hex/http.ex:34: Hex.HTTP.build_http_opts/2
        (hex) lib/hex/http.ex:9: Hex.HTTP.request/5
        (hex) lib/hex/update_checker.ex:29: anonymous fn/0 in Hex.UpdateChecker.handle_cast/2
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
13:31:44.537 [error] Task #PID<0.103.0> started from :hex_fetcher terminating
Function: #Function<15.8841244/0 in Hex.Registry.Server.prefetch_online/2>
    Args: []
** (exit) an exception was raised:
    ** (Mix.Error) Insecure HTTPS request (peer verification disabled), please update to OTP 17.4 or later, or disable by setting the environment variable HEX_UNSAFE_HTTPS=1
        (mix) lib/mix.ex:235: Mix.raise/1
        (hex) lib/hex/http/ssl.ex:38: Hex.HTTP.SSL.secure_ssl?/0
        (hex) lib/hex/http/ssl.ex:49: Hex.HTTP.SSL.ssl_opts/1
        (hex) lib/hex/http.ex:34: Hex.HTTP.build_http_opts/2
        (hex) lib/hex/http.ex:9: Hex.HTTP.request/5
        (hex) lib/hex/registry/server.ex:308: anonymous fn/3 in Hex.Registry.Server.prefetch_online/2
        (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:19: Task.Supervised.async/3
** (exit) exited in: GenServer.call(Hex.Registry.Server, {:versions, "hexpm", "certifi"}, 60000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:356: GenServer.call/3
    (hex) lib/hex/registry/server.ex:54: Hex.Registry.Server.versions/2
    (hex) lib/hex/remote_converger.ex:316: Hex.RemoteConverger.verify_dep/3
    (elixir) lib/enum.ex:543: anonymous fn/3 in Enum.each/2
    (elixir) lib/enum.ex:1266: anonymous fn/3 in Enum.reduce/3
    (elixir) lib/enum.ex:2229: Enumerable.Map.do_reduce/3
    (elixir) lib/enum.ex:1265: Enum.reduce/3
    (elixir) lib/enum.ex:542: Enum.each/2
 !     Push rejected, failed to compile Elixir app.
 !     Push failed
```

**Comment by edgurgel** [comment]
Thanks for raising this issue. I recently changed to use simply docker images. I will see what needs to be done to change the button 🤔 Thanks!

**Comment by 7osCraft** [comment]
How is it now? Does it work
Thanks ☺

**Comment by kofronpi** [comment]
Same question here, I'm investigating if poxa is reliable enough in production to replace pusher which is very costly at scale.

**Comment by edgurgel** [comment]
I just didn't have time to change the button definition :(, but it's basically deploying the docker image. The existing poxa.herokuapp.com uses the docker container that we provide: https://github.com/edgurgel/poxa/blob/master/README.md#using-docker

**Comment by edgurgel** [comment]
Using the docker image is the best way to deploy poxa.. The deploy to heroku button was removed.
